### ISSUE TITLE
There is no license information

### ISSUE THREAD

**Issue by smlavine** [mle86/sh-tests#1]
Hello,
I cannot find any information on what license this project uses. I see in your other projects that they are licensed under either the GPL or MIT licenses, so I assume that you would want this under that license as well. However, if instead you meant to dedicate 
sh-tests to the public domain, be advised that [not having a license does not place code in the public domain.](https://www.gnu.org/licenses/license-list.html#NoLicense) If this is what you intended, I would suggest using a license like [the CC0.](https://creativecommons.org/share-your-work/public-domain/cc0)
-- Sebastian

**Comment by mle86** [comment]
Thank you for your feedback!

I did not pick a license earlier because I had not realized it made using my project more difficult.

This project is now under the MIT license.

**Comment by mle86** [comment]
Thank you for your feedback!

I had not realized that having no license essentially made my project non-free, but that was not my intention.

This project is now licensed under the MIT license.
